# Generated by Django 5.1.2 on 2024-10-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('img', models.FileField(upload_to='imag/')),
                ('zaman_bargozary', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='padcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('file', models.FileField(upload_to='podcasts/')),
                ('tarikhenteshar', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('tarikh', models.DateTimeField(auto_now_add=True)),
                ('berozresani', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tamas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('payam', models.TextField()),
                ('tarikh', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('soal', models.TextField()),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vidio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='vidio/')),
                ('zaman_bargozary', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='consultant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('takhasos', models.CharField(max_length=100)),
                ('biyografi', models.TextField()),
                ('emtiyaz', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typemoshaver', models.CharField(max_length=50)),
                ('tarikh', models.DateField()),
                ('zaman', models.TimeField()),
                ('online', models.BooleanField(default=True)),
                ('makan', models.CharField(blank=True, max_length=255, null=True)),
                ('modat', models.IntegerField(default=30)),
                ('hazine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statu', models.CharField(default='available', max_length=20)),
                ('moshaver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
                ('emtiyaz', models.IntegerField(default=0)),
                ('tarikh', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moshaver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
                ('zaman_ersal', models.DateTimeField(auto_now_add=True)),
                ('ferstande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('girande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mablagh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarikh', models.DateTimeField(auto_now_add=True)),
                ('statu', models.CharField(default='موفق', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
                ('tarikh', models.DateTimeField(auto_now_add=True)),
                ('berozresani', models.DateTimeField(auto_now_add=True)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarikh_rezrv', models.DateTimeField(auto_now_add=True)),
                ('taeed_shod', models.BooleanField(default=False)),
                ('moshaver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
