# Generated by Django 5.1.2 on 2024-10-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_conulationcategory_sabtkarbar_sabtmoshaver'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('file', models.FileField(upload_to='blog/')),
                ('tarikhenteshar', models.DateField()),
            ],
        ),
    ]
