# Generated by Django 5.1.2 on 2024-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabtmoshaver',
            name='saltajrobe',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sabtmoshaver',
            name='savabeghelmi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sabtmoshaver',
            name='savabeghtahsili',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
