# Generated by Django 5.1.2 on 2024-10-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sabtmoshaver_saltajrobe_sabtmoshaver_savabeghelmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='rozhozor',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
