# Generated by Django 5.1.2 on 2024-10-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_consultation_rozhozor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabtmoshaver',
            name='adress',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sabtmoshaver',
            name='adress2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sabtmoshaver',
            name='adress3',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
