# Generated by Django 5.1.2 on 2024-10-30 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sabtmoshaver_city_sabtmoshaver_jensiyat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='typem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='typev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ozviyat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typetakhasos', models.CharField(max_length=100)),
                ('licenc', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='information_m',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namefull', models.CharField(max_length=100)),
                ('codemeli', models.CharField(max_length=100)),
                ('ttavalod', models.CharField(max_length=100)),
                ('jensiyat', models.BooleanField(default=True)),
                ('mizantahsilat', models.CharField(max_length=100)),
                ('typemadrak', models.CharField(max_length=100)),
                ('savabeghtahsili', models.CharField(max_length=250)),
                ('savabeghelmi', models.CharField(max_length=250)),
                ('saltajrobe', models.CharField(max_length=250)),
                ('ostan', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('adress', models.CharField(max_length=250)),
                ('tell', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imag', models.ImageField(upload_to='files/moshaver')),
                ('zaman', models.TimeField()),
                ('modat', models.IntegerField(default=30)),
                ('hazine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rozhozor', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('biyografi', models.TextField()),
                ('statu', models.CharField(default='available', max_length=20)),
                ('emtiyaz', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('typetakhasos', models.ManyToManyField(to='app.typem')),
                ('online', models.ManyToManyField(to='app.typev')),
            ],
        ),
    ]
