# Generated by Django 5.1.2 on 2024-10-30 08:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_typem_typev_ozviyat_information_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_m',
            name='datetime',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
