# Generated by Django 5.1.2 on 2024-11-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_information_m_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_m',
            name='emtiyaz',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information_m',
            name='hazine',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
