# Generated by Django 5.1.2 on 2024-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_information_m_ttavalod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_m',
            name='jensiyat',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
