# Generated by Django 5.1.2 on 2024-11-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_information_m_jensiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_m',
            name='codemeli',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='information_m',
            name='emtiyaz',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='information_m',
            name='hazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='information_m',
            name='modat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='information_m',
            name='tell',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='information_m',
            name='zaman',
            field=models.IntegerField(null=True),
        ),
    ]
