# Generated by Django 5.1.2 on 2024-11-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_information_m_codemeli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='پاسخ داده شد', max_length=20, null=True),
        ),
    ]
