# Generated by Django 5.1.2 on 2024-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_m',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
