# Generated by Django 5.1.2 on 2024-11-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_information_m_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_m',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
