# Generated by Django 5.1.2 on 2024-11-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_answer_user_image_user_padcast_user_question_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padcast',
            name='file',
            field=models.FileField(upload_to='files/padcast'),
        ),
    ]
