# Generated by Django 5.1.2 on 2024-11-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_padcast_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padcast',
            name='file',
            field=models.FileField(null=True, upload_to='files/padcast'),
        ),
    ]
