# Generated by Django 5.1.2 on 2024-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_padcast_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padcast',
            name='tarikhenteshar',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
