# Generated by Django 5.1.2 on 2024-11-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_information_m_image1_information_m_padcast1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_m',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='information_m',
            name='padcast1',
        ),
        migrations.RemoveField(
            model_name='information_m',
            name='test1',
        ),
        migrations.RemoveField(
            model_name='information_m',
            name='vidio1',
        ),
        migrations.AddField(
            model_name='image',
            name='moshaver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.information_m'),
        ),
        migrations.AddField(
            model_name='padcast',
            name='moshaver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.information_m'),
        ),
        migrations.AddField(
            model_name='test',
            name='moshaver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.information_m'),
        ),
        migrations.AddField(
            model_name='vidio',
            name='moshaver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.information_m'),
        ),
    ]
