# Generated by Django 5.1.2 on 2024-11-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_information_m_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
