# Generated by Django 5.1.2 on 2024-11-19 14:47

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_timeslot_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'saturday'), (1, 'sunday'), (2, 'monday'), (3, ' tuesday'), (4, 'wednesday'), (5, 'thursday'), (6, 'friday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.information_m')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField()),
                ('date1', models.DateField()),
                ('time', models.TimeField()),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.information_m')),
            ],
            options={
                'unique_together': {('consultant', 'date', 'time')},
            },
        ),
    ]
