# Generated by Django 5.1.1 on 2024-11-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_availability_consultant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
