# Generated by Django 5.1.1 on 2024-11-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_delete_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appintment',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='appintment',
            name='is_confirmed',
        ),
    ]
