# Generated by Django 5.1.1 on 2024-12-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_message_ferstande_alter_message_girande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabtkarbar',
            name='password',
        ),
        migrations.RemoveField(
            model_name='sabtkarbar',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='sabtkarbar',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='sabtkarbar',
            name='username',
        ),
        migrations.AddField(
            model_name='sabtkarbar',
            name='codemeli',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sabtkarbar',
            name='namefull',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
