# Generated by Django 5.1.1 on 2024-12-01 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_sabtkarbar_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appintment',
            name='codemeli',
        ),
        migrations.RemoveField(
            model_name='appintment',
            name='namefull',
        ),
        migrations.RemoveField(
            model_name='appintment',
            name='tel',
        ),
        migrations.AddField(
            model_name='appintment',
            name='karbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sabtkarbar', verbose_name=''),
        ),
    ]
