# Generated by Django 5.1.1 on 2024-12-04 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_appintment_codemeli_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='ferstande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.information_m'),
        ),
        migrations.AlterField(
            model_name='message',
            name='girande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sabtkarbar'),
        ),
    ]
