# Generated by Django 5.1.1 on 2024-12-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_image_moshaver_remove_padcast_moshaver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_m',
            name='image',
        ),
        migrations.RemoveField(
            model_name='information_m',
            name='padcast',
        ),
        migrations.RemoveField(
            model_name='information_m',
            name='test',
        ),
        migrations.RemoveField(
            model_name='information_m',
            name='vidio',
        ),
    ]
