# Generated by Django 5.1.1 on 2024-12-10 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_tamas_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appintment',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.information_m'),
        ),
        migrations.AlterField(
            model_name='appintment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appintment',
            name='karbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appintment',
            name='time',
            field=models.TimeField(),
        ),
    ]
