# Generated by Django 5.1.1 on 2024-12-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_m',
            name='codemeli',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='information_m',
            name='email',
            field=models.EmailField(max_length=250, null=True, unique=True),
        ),
    ]
