# Generated by Django 5.1.1 on 2024-12-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_m',
            name='rozonline',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
