# Generated by Django 5.1.2 on 2025-01-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_sabtkarbar_user_delete_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ozviyat',
        ),
    ]
