# Generated by Django 5.1.2 on 2025-01-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_delete_ozviyat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='moshaver',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='moshaver',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appintment',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='consultant',
        ),
        migrations.DeleteModel(
            name='consultation',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
