# Generated by Django 5.1.2 on 2024-12-17 11:03

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='typem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='typev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='information_m',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namefull', models.CharField(max_length=100)),
                ('codemeli', models.IntegerField(null=True)),
                ('datetime', django_jalali.db.models.jDateField(null=True)),
                ('jensiyat', models.CharField(max_length=20, null=True)),
                ('mizantahsilat', models.CharField(max_length=100)),
                ('typemadrak', models.CharField(max_length=100)),
                ('savabeghtahsili', models.CharField(max_length=250)),
                ('savabeghelmi', models.CharField(max_length=250)),
                ('saltajrobe', models.CharField(max_length=250)),
                ('ostan', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('adress', models.CharField(max_length=250)),
                ('tell', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imag', models.ImageField(upload_to='files/moshaver')),
                ('zaman', models.IntegerField(null=True)),
                ('modat', models.IntegerField(null=True)),
                ('hazine', models.IntegerField(null=True)),
                ('rozhozor', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('biyografi', models.TextField()),
                ('statu', models.CharField(default='available', max_length=20)),
                ('emtiyaz', models.IntegerField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('shomarehesab', models.CharField(max_length=250)),
                ('name_saheb_hesab', models.CharField(max_length=250)),
                ('shaba', models.CharField(max_length=250)),
                ('typetakhasos', models.ManyToManyField(to='dashboard.typem')),
                ('online', models.ManyToManyField(to='dashboard.typev')),
            ],
        ),
    ]
