# Generated by Django 5.1.2 on 2024-12-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mablagh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarikh', models.DateTimeField(auto_now_add=True)),
                ('statu', models.CharField(default='موفق', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appintment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.information_m')),
            ],
        ),
    ]
