# Generated by Django 5.1.2 on 2024-12-17 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_payment_appintment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.information_m'),
        ),
    ]
