# Generated by Django 5.1.2 on 2024-12-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_payment_consultant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appintment',
            options={'verbose_name': 'رزرو نوبت'},
        ),
        migrations.AlterModelOptions(
            name='information_m',
            options={'verbose_name': 'مشاوران'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت ها '},
        ),
    ]
