# Generated by Django 5.1.1 on 2024-12-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_appintment_options_alter_information_m_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
            ],
            options={
                'verbose_name': 'درباره ی ما  ',
            },
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('file', models.FileField(upload_to='blog/')),
                ('tarikhenteshar', models.DateField()),
            ],
            options={
                'verbose_name': ' مطالب و وبلاگ',
            },
        ),
        migrations.CreateModel(
            name='tamas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('payam', models.TextField()),
                ('ip', models.CharField(max_length=50, null=True)),
                ('tarikh', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ' نظرات ',
            },
        ),
    ]
