# Generated by Django 5.1.2 on 2025-01-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_about_blog_tamas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
