# Generated by Django 5.1.1 on 2024-12-31 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0046_information_m_rozonline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appintment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerv_appointments', to='app.information_m')),
                ('karbar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rezerv_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
