# Generated by Django 5.1.1 on 2024-12-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appintment',
            name='appointment_type',
            field=models.CharField(choices=[('online', 'آنلاین'), ('offline', 'حضوری')], max_length=10, null=True),
        ),
    ]
