# Generated by Django 5.1.1 on 2025-01-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerv', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagesaval', to='rezerv.appointment'),
        ),
    ]
